[package]
name    = "order_service"
version = "0.0.0"
edition = "2024"

[dependencies]
actix-web  = "4.10.2"
sqlx       = { version = "0.8.5", features = ["sqlite", "runtime-tokio"] }
serde      = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
